apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ualflix
  labels:
    app: prometheus
    component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'ualflix-k8s'
        environment: 'production'

    rule_files:
      - "/etc/prometheus/alert.rules"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - ualflix
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

      - job_name: 'ualflix-services'
        static_configs:
          - targets: 
              - 'auth-service:80'
              - 'catalog-service:80'
              - 'streaming-service:80'
              - 'admin-service:80'
              - 'video-processor-service:80'
        metrics_path: '/metrics'
        scrape_interval: 10s

      - job_name: 'rabbitmq'
        static_configs:
          - targets: ['rabbitmq-service:15692']
        metrics_path: '/metrics'
        scrape_interval: 30s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

  alert.rules: |
    groups:
      - name: ualflix_k8s_alerts
        rules:
          - alert: PodDown
            expr: up{job="ualflix-services"} == 0
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "Pod {{ $labels.instance }} is down"
              description: "Pod {{ $labels.instance }} has been down for more than 30 seconds"

          - alert: HighMemoryUsage
            expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.8
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{ $labels.pod }}"
              description: "Memory usage is above 80% on {{ $labels.pod }}"

          - alert: HighCPUUsage
            expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{ $labels.pod }}"
              description: "CPU usage is above 80% on {{ $labels.pod }}"