apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: ualflix
  labels:
    app: mongodb
    component: database
data:
  init-replica.js: |
    rs.initiate({
      _id: "ualflix-replica-set",
      members: [
        { _id: 0, host: "mongodb-0.mongodb-service.ualflix.svc.cluster.local:27017", priority: 2 },
        { _id: 1, host: "mongodb-1.mongodb-service.ualflix.svc.cluster.local:27017", priority: 1 },
        { _id: 2, host: "mongodb-2.mongodb-service.ualflix.svc.cluster.local:27017", arbiterOnly: true }
      ]
    });
  
  create-users.js: |
    db = db.getSiblingDB('admin');
    db.createUser({
      user: process.env.MONGO_INITDB_ROOT_USERNAME,
      pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
      roles: [ { role: 'root', db: 'admin' } ]
    });
    
    db = db.getSiblingDB('ualflix');
    db.createUser({
      user: process.env.MONGO_INITDB_USERNAME,
      pwd: process.env.MONGO_INITDB_PASSWORD,
      roles: [
        { role: 'readWrite', db: 'ualflix' },
        { role: 'dbAdmin', db: 'ualflix' }
      ]
    });