apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  namespace: ualflix
  labels:
    app: mongodb
    component: database
spec:
  template:
    metadata:
      labels:
        app: mongodb
        component: database
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongodb-init
        image: mongo:6.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-root-password
        - name: MONGO_INITDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-username
        - name: MONGO_INITDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-password
        command:
        - bash
        - -c
        - |
          echo "Waiting for MongoDB instances..."
          until mongo --host mongodb-0.mongodb-service.ualflix.svc.cluster.local:27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            echo "Waiting for MongoDB-0 to be ready..."
            sleep 5
          done
          
          until mongo --host mongodb-1.mongodb-service.ualflix.svc.cluster.local:27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            echo "Waiting for MongoDB-1 to be ready..."
            sleep 5
          done
          
          until mongo --host mongodb-2.mongodb-service.ualflix.svc.cluster.local:27017 --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            echo "Waiting for MongoDB-2 to be ready..."
            sleep 5
          done
          
          echo "Initializing Replica Set..."
          mongo --host mongodb-0.mongodb-service.ualflix.svc.cluster.local:27017 --eval "$(cat /scripts/init-replica.js)"
          
          echo "Waiting for Replica Set to stabilize..."
          sleep 30
          
          echo "Creating users..."
          mongo --host mongodb-0.mongodb-service.ualflix.svc.cluster.local:27017 --eval "$(cat /scripts/create-users.js)"
          
          echo "MongoDB initialization completed!"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: mongodb-config

---