apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ualflix
  labels:
    app: nginx
    component: proxy
    service: load-balancer
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080  # Porta externa para acesso
  type: NodePort  # Permite acesso externo
  externalTrafficPolicy: Local