apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ualflix
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
  namespace: ualflix
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ik4rm4/admin_service:latest
          ports:
            - containerPort: 5002