apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: ualflix
  labels:
    app: admin
    component: backend
spec:
  replicas: 1  # Admin service não precisa de múltiplas réplicas
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
        component: backend
    spec:
      containers:
        - name: admin
          image: admin_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
      restartPolicy: Always
