apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: ualflix
  labels:
    app: admin
    component: backend
spec:
  selector:
    app: admin
  ports:
    - name: http
      port: 80
      targetPort: 8002
      protocol: TCP
  type: ClusterIP