apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ualflix
  name: streaming-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
  namespace: ualflix
      labels:
        app: streaming
    spec:
      containers:
        - name: streaming
          image: ik4rm4/streaming_service:latest
          ports:
            - containerPort: 5001