apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: ualflix
  labels:
    app: streaming
    component: backend
spec:
  selector:
    app: streaming
  ports:
    - name: http
      port: 80
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
  # Para streaming, manter sessão no mesmo pod pode ser útil
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300