apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: ualflix
spec:
  type: NodePort
  selector:
    app: nginx-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Você pode escolher outra porta entre 30000-32767 se quiser