apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: ualflix
  labels:
    app: admin-service
    tier: backend
    component: admin
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        tier: backend
        component: admin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - name: wait-for-mongodb
        image: mongo:6.0
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-password
        command: ['sh', '-c']
        args:
        - |
          echo "Aguardando MongoDB..."
          until mongosh --host mongodb-0.mongodb-headless.ualflix.svc.cluster.local -u $MONGODB_USERNAME -p $MONGODB_PASSWORD --authenticationDatabase admin --eval "rs.status()" >/dev/null 2>&1; do
            echo "MongoDB não está pronto..."
            sleep 5
          done
          echo "MongoDB está pronto!"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
      containers:
      - name: admin-service
        image: admin_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
          name: http
          protocol: TCP
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://admin:$(MONGODB_PASSWORD)@mongodb-0.mongodb-headless.ualflix.svc.cluster.local:27017,mongodb-1.mongodb-headless.ualflix.svc.cluster.local:27017,mongodb-2.mongodb-headless.ualflix.svc.cluster.local:27017/ualflix?replicaSet=ualflix-replica-set&authSource=admin"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-password
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_DATABASE
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_USERNAME
        - name: MONGODB_REPLICA_SET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_REPLICA_SET
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        - name: CATALOG_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CATALOG_SERVICE_URL
        - name: STREAMING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: STREAMING_SERVICE_URL
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-storage
          mountPath: /tmp
      volumes:
      - name: tmp-storage
        emptyDir: {}