apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: ualflix
  labels:
    app: admin-service
    tier: backend
    component: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        tier: backend
        component: admin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: admin-service
        image: admin_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
