# k8s/secrets.yaml
# FUNCIONALIDADE 5: REPLICAÇÃO DE DADOS - Secrets para MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ualflix
  labels:
    app: ualflix
    component: secrets
type: Opaque
data:
  # MongoDB credentials (base64 encoded)
  mongodb-root-password: cGFzc3dvcmQ=        # "password"
  mongodb-username: YWRtaW4=                 # "admin" 
  mongodb-password: cGFzc3dvcmQ=             # "password"
  mongodb-database: dWFsZmxpeA==             # "ualflix"
  
  # RabbitMQ credentials
  rabbitmq-password: dWFsZmxpeF9wYXNzd29yZA==  # "ualflix_password"
  
  # JWT secret for authentication
  jwt-secret: dWFsZmxpeC1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # "ualflix-secret-key-change-in-production"
---
# ConfigMap para configurações não-sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ualflix
  labels:
    app: ualflix
    component: config
data:
  # MongoDB Configuration
  MONGODB_PRIMARY_HOST: "mongodb-service"
  MONGODB_PRIMARY_PORT: "27017"
  MONGODB_DATABASE: "ualflix"
  MONGODB_USERNAME: "admin"
  
  # RabbitMQ Configuration
  QUEUE_HOST: "rabbitmq-service"
  QUEUE_USER: "ualflix"
  
  # Service URLs para comunicação interna
  AUTH_SERVICE_URL: "http://auth-service:8000"
  CATALOG_SERVICE_URL: "http://catalog-service:8000"
  STREAMING_SERVICE_URL: "http://streaming-service:8001"
  ADMIN_SERVICE_URL: "http://admin-service:8002"
  VIDEO_PROCESSOR_URL: "http://video-processor-service:8000"
  
  # NGINX Gateway URLs
  NGINX_GATEWAY_URL: "http://nginx-gateway:8080"
  NGINX_INTERNAL_URL: "http://nginx-gateway-internal"
  
  # Monitoring URLs
  PROMETHEUS_URL: "http://prometheus-service:9090"
  GRAFANA_URL: "http://grafana-service:3000"
  
  # Application Settings
  FLASK_ENV: "development"
  FLASK_DEBUG: "1"
  LOG_LEVEL: "INFO"
  
  # Cluster Settings
  CLUSTER_MODE: "kubernetes"
  NODE_COUNT: "3"
  REPLICA_COUNT: "3"