# SECRETS - Configurações sensíveis com MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ualflix
  labels:
    app: ualflix
type: Opaque
data:
  # MongoDB credentials (base64)
  mongodb-root-password: bW9uZ29fcGFzcw==  # "mongo_pass"
  mongodb-username: dWFsZmxpeA==           # "ualflix"
  mongodb-password: dWFsZmxpeF9wYXNz       # "ualflix_pass"
  mongodb-database: dWFsZmxpeA==           # "ualflix"
  
  # RabbitMQ credentials
  rabbitmq-password: dWFsZmxpeF9wYXNzd29yZA==  # "ualflix_password"
  
  # JWT secret
  jwt-secret: dWFsZmxpeC1zZWNyZXQta2V5  # "ualflix-secret-key"
---
# ConfigMap para configurações não-sensíveis
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ualflix
  labels:
    app: ualflix
data:
  # MongoDB Configuration
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "ualflix"
  MONGODB_USERNAME: "ualflix"
  
  # RabbitMQ Configuration
  QUEUE_HOST: "rabbitmq-service"
  QUEUE_USER: "ualflix"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8000"
  CATALOG_SERVICE_URL: "http://catalog-service:8000"
  STREAMING_SERVICE_URL: "http://streaming-service:8001"
  ADMIN_SERVICE_URL: "http://admin-service:8002"
