apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ualflix
  name: video-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
  namespace: ualflix
      labels:
        app: video-processor
    spec:
      containers:
        - name: video-processor
          image: ik4rm4/video_processor:latest
          ports:
            - containerPort: 5003