apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-deployment
  namespace: ualflix
  labels:
    app: video-processor
    component: worker
spec:
  replicas: 2  # Múltiplos workers para processar vídeos
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
        component: worker
    spec:
      containers:
        - name: video-processor
          image: video_processor:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: QUEUE_HOST
              value: "rabbitmq-service"
            - name: QUEUE_USER
              value: "ualflix"
            - name: QUEUE_PASSWORD
              value: "ualflix_password"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"  # Processamento de vídeo precisa mais memória
              cpu: "1500m"
          volumeMounts:
            - name: video-storage
              mountPath: /videos
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 2
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: video-storage-pvc
      restartPolicy: Always