apiVersion: v1
kind: Service
metadata:
  name: video-processor-service
  namespace: ualflix
  labels:
    app: video-processor
    component: worker
spec:
  selector:
    app: video-processor
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP