apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ualflix
  labels:
    app: frontend
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend 