apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ualflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "ualflix"
        - name: RABBITMQ_DEFAULT_PASS
          value: "ualflix_password"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: ualflix
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
