apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: ualflix
  labels:
    app: rabbitmq
    component: messaging
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: management
    port: 15672
    targetPort: 15672
    protocol: TCP
  - name: prometheus
    port: 15692
    targetPort: 15692
    protocol: TCP
  type: ClusterIP