apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ualflix
data:
  POSTGRES_DB: ualflix
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust