apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-primary
  namespace: ualflix
data:
  postgresql.conf: |
    # Configuração PostgreSQL Primary para Kubernetes
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    
    # Memory
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    
    # WAL - Essencial para replicação
    wal_level = replica
    archive_mode = on
    archive_command = 'test ! -f /var/lib/postgresql/archive/%f && cp %p /var/lib/postgresql/archive/%f'
    max_wal_senders = 3
    wal_keep_size = 1GB
    hot_standby = on
    
    # Replication
    synchronous_standby_names = ''
    wal_sender_timeout = 60s
    wal_receiver_timeout = 60s
    
    # Logging
    logging_collector = on
    log_destination = 'stderr'
    log_min_duration_statement = 1000
    
    # Checkpoints
    checkpoint_completion_target = 0.9
    checkpoint_timeout = 5min
