# SERVIÇO DE AUTENTICAÇÃO com MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ualflix
  labels:
    app: auth-service
    tier: backend
    component: authentication
spec:
  replicas: 2  # Redundância para serviço crítico
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
        component: authentication
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: mongo:6.0
        command: ['sh', '-c']
        args:
        - |
          until mongosh --host mongodb-service --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
            echo "Aguardando MongoDB..."
            sleep 2
          done
          echo "MongoDB pronto!"
      containers:
      - name: auth-service
        image: authentication_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_HOST
        - name: MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_PORT
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_DATABASE
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
