apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ualflix
  name: catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
  namespace: ualflix
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: ik4rm4/catalog_service:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "postgres-primary"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "ualflix"