apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: ualflix
  labels:
    app: catalog
    component: backend
spec:
  replicas: 3  # Múltiplas réplicas para alta disponibilidade
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        component: backend
    spec:
      containers:
        - name: catalog
          image: catalog_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DB_MASTER_HOST
              value: "postgres-primary-service"
            - name: DB_SLAVE_HOST
              value: "postgres-replica-service"
            - name: DB_NAME
              value: "ualflix"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: QUEUE_HOST
              value: "rabbitmq-service"
            - name: QUEUE_USER
              value: "ualflix"
            - name: QUEUE_PASSWORD
              value: "ualflix_password"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: video-storage
              mountPath: /videos
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: video-storage-pvc
      restartPolicy: Always