apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ualflix
  labels:
    app: catalog
    component: backend
spec:
  selector:
    app: catalog
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
  sessionAffinity: None